export const QUERY_COMMENTS = 'QUERY_COMMENTS';
export type QUERY_COMMENTS = typeof QUERY_COMMENTS;

export const QUERY_COMMENTS_SUCCESS = 'QUERY_COMMENTS_SUCCESS';
export type QUERY_COMMENTS_SUCCESS = typeof QUERY_COMMENTS_SUCCESS;

export const QUERY_COMMENTS_ERROR = 'QUERY_COMMENTS_ERROR';
export type QUERY_COMMENTS_ERROR = typeof QUERY_COMMENTS_ERROR;