export const QUERY_PROFILE = 'QUERY_PROFILE';
export type QUERY_PROFILE = typeof QUERY_PROFILE;

export const QUERY_PROFILE_SUCCESS = 'QUERY_PROFILE_SUCCESS';
export type QUERY_PROFILE_SUCCESS = typeof QUERY_PROFILE_SUCCESS;

export const QUERY_PROFILE_ERROR = 'QUERY_PROFILE_ERROR';
export type QUERY_PROFILE_ERROR = typeof QUERY_PROFILE_ERROR;